name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON
      
    - name: Build
      run: cmake --build build --config Debug
      
    - name: Run Tests
      run: cd build && ctest --output-on-failure
